dataset: modified_bgl_train_0-1w.json,modified_bgl_train_1-2w.json,modified_bgl_train_2-3w.json,modified_bgl_train_3-4w.json
dataset_dir: "/home/admin1/\u684C\u9762/LLaMA-Factory/data"
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 50
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: q_proj,v_proj
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: "/home/admin1/\u684C\u9762/Meta-Llama-3-8B-Instruct"
num_train_epochs: 1.0
optim: adamw_torch
output_dir: saves/LLaMA3-8B-Chat/lora/train_bgl_4w
packing: false
per_device_train_batch_size: 1
report_to: none
save_steps: 1000
stage: sft
template: llama3
warmup_steps: 0
