dataset: modified_Tbird_train_0-2w_Drain.json,modified_Tbird_train_2-4w_Drain.json
dataset_dir: "/home/admin1/\u684C\u9762/LLaMA-Factory/data/"
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 50
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: q_proj,v_proj
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: "/home/admin1/\u684C\u9762/Meta-Llama-3-8B-Instruct"
num_train_epochs: 1.0
optim: adamw_torch
output_dir: saves/LLaMA3-8B-Chat/lora/train_Tbird
packing: false
per_device_train_batch_size: 1
report_to: none
save_steps: 500
stage: sft
template: llama3
use_dora: true
warmup_steps: 0
